### PR TITLE
fixes for #41,

### PR DESCRIPTION
**Pull request by marcvelasco**
add gulp-install to package.json for frontend, fix readme for backend startup

Let me know any changes needed!

### CODE REVIEW

**Comment by upkarlidder** [comment]
Thanks @demilolu. I am going to clone and review tomorrow. 

@marcvelasco thank you for working on this. I am wondering if gulp is a requirement? I don't see it in package.json. Where is it being used?

**Comment by marcvelasco** [comment]
If you pull the current master and do an "npm install" in the frontend directory you'll receive this error, looking like a dependancy for the semantic-ui module, i can see some gulp config files in there defining tasks for that module:

Here's the install error:
```
npm install
npm ERR! code 1
npm ERR! path /Users/mvelasc@us.ibm.com/working/Incident-Accuracy-Reporting-System/frontend/node_modules/semantic-ui
npm ERR! command failed
npm ERR! command sh -c gulp install
npm ERR! fs.js:52
npm ERR! } = primordials;
npm ERR!     ^
npm ERR! 
npm ERR! ReferenceError: primordials is not defined
npm ERR!     at fs.js:52:5
npm ERR!     at req_ (/Users/mvelasc@us.ibm.com/working/Incident-Accuracy-Reporting-System/frontend/node_modules/natives/index.js:143:24)
npm ERR!     at Object.req [as require] (/Users/mvelasc@us.ibm.com/working/Incident-Accuracy-Reporting-System/frontend/node_modules/natives/index.js:55:10)
npm ERR!     at Object.<anonymous> (/Users/mvelasc@us.ibm.com/working/Incident-Accuracy-Reporting-System/frontend/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1108:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:973:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:997:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:92:18)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mvelasc@us.ibm.com/.npm/_logs/2021-10-15T02_26_47_572Z-debug.log
```
if you add `"gulp-install": "^1.1.0",` to your package.json you can run npm install without error for the front end.

**Comment by demilolu** [comment]
@marcvelasco Thanks again for your contribution to our projects! We would like to invite you to join us for our Hacktoberfest Demo Day on  October 29th where we'll be highlighting contributions and thanking everyone who participated. Let me know if you can make it! https://www.crowdcast.io/e/hacktoberfest-demo-day/register 

also if you're able to say a few words on gulp-install during the event let me know! and I can connect with you on that.

**Comment by marcvelasco** [comment]
@demilolu Sure thing would love to attend and say a few words.

**Comment by demilolu** [comment]
perfect! Are you in our slack channel. want to chat there so we can coordinate if possible. callforcode.org/slack, if email works better let me know.

**Pull request closed without merging**
