### PR TITLE
Changed operational model diagram

### PR DESCRIPTION
**Pull request by blackpandan**
i changed the operational model diagram to suit github darkmode.

### CODE REVIEW

**Comment by krook** [comment]
Thanks for the pulll request @blackpandan!

- Does it work in both modes? 
- Can you submit the new image as a commit with this pull request, rather than referring to an external URL?

**Comment by blackpandan** [comment]
yes, it works in both mode, alright I would submit the image.

**Comment by krook** [comment]
Thanks again @blackpandan. Are you pushing a new commit for the image?

**Comment by blackpandan** [comment]
I pushed a new pull request for the image, sorry.

**Comment by krook** [comment]
Superseded by #34. Thanks again @blackpandan

**Pull request closed without merging**
